CREATE TABLE `fixtures` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Date` int DEFAULT NULL,
  `Team_1_ID` int NOT NULL,
  `Team_2_ID` int NOT NULL,
  `Location_ID` int NOT NULL,
  `Season_ID` int NOT NULL,
  `League_ID` int DEFAULT NULL,
  `Cup_ID` int DEFAULT NULL,
  `Team_1_Score` int DEFAULT NULL,
  `Team_2_Score` int DEFAULT NULL,
  `Elo_Change` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `fixture_id_UNIQUE` (`ID`),
  KEY `FK_fixtures_teams_1_idx` (`Team_1_ID`),
  KEY `FK_fixtures_teams_2_idx` (`Team_2_ID`),
  KEY `FK_fixtures_locations_idx` (`Location_ID`),
  KEY `FK_fixtures_seasons_idx` (`Season_ID`),
  KEY `FK_fixtures_leagues_idx` (`League_ID`),
  KEY `FK_fixtures_cups_idx` (`Cup_ID`),
  CONSTRAINT `FK_fixtures_cups` FOREIGN KEY (`Cup_ID`) REFERENCES `cups` (`ID`),
  CONSTRAINT `FK_fixtures_leagues` FOREIGN KEY (`League_ID`) REFERENCES `leagues` (`ID`),
  CONSTRAINT `FK_fixtures_locations` FOREIGN KEY (`Location_ID`) REFERENCES `locations` (`ID`),
  CONSTRAINT `FK_fixtures_seasons` FOREIGN KEY (`Season_ID`) REFERENCES `seasons` (`ID`),
  CONSTRAINT `FK_fixtures_teams_1` FOREIGN KEY (`Team_1_ID`) REFERENCES `teams` (`ID`),
  CONSTRAINT `FK_fixtures_teams_2` FOREIGN KEY (`Team_2_ID`) REFERENCES `teams` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
