// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

namespace Web.Migrations
{
    [DbContext(typeof(ShrContext))]
    [Migration("20210418123553_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Web.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Hockey_Category_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Web.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Hockey_Category_ID")
                        .HasColumnType("int");

                    b.Property<int?>("League_ID")
                        .HasColumnType("int");

                    b.Property<int?>("League_Rank")
                        .HasColumnType("int");

                    b.Property<int>("Movement")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("SeasonDrawn")
                        .HasColumnType("int");

                    b.Property<int>("SeasonGoalDifference")
                        .HasColumnType("int");

                    b.Property<int>("SeasonGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("SeasonGoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("SeasonLost")
                        .HasColumnType("int");

                    b.Property<int>("SeasonPlayed")
                        .HasColumnType("int");

                    b.Property<int>("SeasonPoints")
                        .HasColumnType("int");

                    b.Property<int>("SeasonWon")
                        .HasColumnType("int");

                    b.Property<string>("Sponsor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Teamname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TotalDrawn")
                        .HasColumnType("int");

                    b.Property<int>("TotalGoalDifference")
                        .HasColumnType("int");

                    b.Property<int>("TotalGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("TotalGoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("TotalLost")
                        .HasColumnType("int");

                    b.Property<int>("TotalPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalWon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
